#pragma once
#include "../wallet/clob_auth.hpp"
#include "../wallet/eip712.hpp"
#include <array>
#include <string>

// REST client for the Polymarket CLOB API.
//
// Base URL: https://clob.polymarket.com
// Endpoints used:
//   POST   /order       — submit a signed order
//   DELETE /order/{id}  — cancel an open order
//   GET    /order/{id}  — poll order status
//
// Every mutating request carries Level 2 auth headers generated by ClobAuth.
// This class is NOT thread-safe — instantiate one per thread or synchronise externally.
// (Thread 3 owns a single instance.)
//
// libcurl must be globally initialised (curl_global_init) before use.

namespace execution {

class ClobClient {
public:
    enum class OrderState { UNKNOWN, OPEN, MATCHED, FILLED, CANCELLED };

    struct SubmitResult {
        bool        success  = false;
        std::string order_id;
        double      price    = 0.0;
        std::string error;
    };

    struct OrderStatus {
        OrderState  state        = OrderState::UNKNOWN;
        double      size_matched = 0.0;
        double      avg_price    = 0.0;
    };

    explicit ClobClient(std::string base_url = "https://clob.polymarket.com");

    // Submit a signed order.
    // order_type: "GTC", "IOC", or "FOK"
    SubmitResult submit_order(const wallet::Order&           order,
                               const std::array<uint8_t,65>& sig,
                               const wallet::ClobAuth&        auth,
                               std::string_view               order_type);

    // Cancel an open order by ID.  Returns true on HTTP 200.
    bool cancel_order(const std::string&      order_id,
                      const wallet::ClobAuth& auth);

    // Poll order status.
    OrderStatus get_status(const std::string& order_id);

private:
    std::string post(const std::string& path, const std::string& body,
                     const std::map<std::string, std::string>& headers);
    std::string get (const std::string& path);
    std::string del (const std::string& path,
                     const std::map<std::string, std::string>& headers);

    std::string base_url_;
};

// Parse a decimal-string token ID (Polymarket CTF token) into a big-endian uint256_t.
// Throws std::invalid_argument if the string is empty or not a valid decimal.
wallet::uint256_t parse_token_id(const std::string& decimal_str);

} // namespace execution
